### ISSUE TITLE
Unable to open Opensearch Dashboard

### ISSUE THREAD

**Issue by seano10** [aws-solutions/qnabot-on-aws#796]
**Describe the bug**
I may just be missing something obvious but when I click to go to the Opensearch Dashboards (which was previously working) I get the attached error.

**To Reproduce**
Can be reproduced every time by clicking on 'Opensearch Dashboards'

**Expected behavior**
I would expect it opened the Opensearch Dashboards correctly

**Please complete the following information about the solution:**
Version: 6.1.0
BuildDate: Wed Aug 28 2024 23:00:22 GMT

- [ ] Region: eu-west-2 (London)
- [ ] Was the solution modified from the version published on this repository? - NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? - N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? N/A
- [ ] Were there any errors in the CloudWatch Logs? - NO

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
I kind of understand what the error is saying but I am confused as it used to work and nothing external to the solution has changed that I am aware of.
![opensearch error](https://github.com/user-attachments/assets/b8d6302f-ecad-4075-9447-2c25b73e1e02)

**Comment by abhirpat** [comment]
Hi @seano10 , thank you for reporting this. What happens when click on 'Log in to OpenSearch Dashboards' button below 'Sorry!' emoji?

**Comment by seano10** [comment]
Hi @abhirpat , if I click the button below 'sorry' it asks for my credentials which I supply and then it gives the same error again

**Comment by abhirpat** [comment]
Thank you for that information. Could you please also try following steps?
1. Logout and clear cache or incognito mode in the browser. Open Content Designer > select the tools menu ( ☰ ) > click on OpenSearch Dashboard.
2. Also, please try latest version of QnABot v6.1.5. Because I noticed you are using v6.1.0 and I'd like to see if fixes in v6.1.2 help with this.

**Comment by seano10** [comment]
Thanks, I have tried (1), no luck  I will have to try (2) in the morning as I need to knock off for the day now I'm afraid, thanks I will update further when I have tried.  For (3) it is the default admin as setup when I deployed the version last time.

**Comment by seano10** [comment]
Hi @abhirpat I have upgraded to  6.1.5 but still get the same error...  Also to confirm the Admin looks to have all the correct configuration as per the 'troubleshooting' link from the 'Sorry' error message that pops up.

**Comment by abhirpat** [comment]
Thank you @seano10 for validating that. Going back to the error, it seems that something has changed between identity pool and assigned IAM roles. In the post, you have mentioned that it was working before. Do you recall what changes you made before it stopped working? Were there any changes in the trust relationships of roles or modifications to the authentication?

**Comment by seano10** [comment]
Hi @abhirpat sorry for the slow reply, no I am not aware of any changes that were made to anything, certainly I made none and no one else has cause to be doing so.  It is strange as if I check the identity pools and roles it all looks to be setup correctly.

**Comment by abhirpat** [comment]
Hi @seano10, this error typically occurs when there's a misconfiguration between Amazon Cognito and OpenSearch Dashboards, specifically related to IAM roles. I have tried to deploy few QnABot instances but unable to reproduce.

Here's how we can troubleshoot the issue. Please -

1.  Navigate to IAM role ESCognitoRole's policy  > AWSQnaBotESCognitoAccess policy. Please ensure this policy was not modified. 
2. In the statement where there is `cognito-idp:ListUserPoolClients`. Please try adding `cognito-idp:UpdateUserPoolClient`
3. In statement where the action is `"Action": "iam:PassRole"`, please try 
    a. add `"iam:GetRole"` as an additional action
    b. add following resource `arn:aws:iam::<account-id>:role/service-role/CognitoAccessForAmazonOpenSearch` where `<account-id>` is the account id you need to substitute.

Here is the [OpenSearch](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cognito-auth.html) documentation for examples on how to policies can be set 

Please let me know that resolves issue.
 
 Thank you,
 Abhishek

**Comment by seano10** [comment]
Thanks @abhirpat , assuming I have updated the above correctly (attached) this has had no effect, I still get the 'Sorry' message
![IAM Updates](https://github.com/user-attachments/assets/45fdb606-6d61-4dfb-a5b6-e94cdec7fa50)

**Comment by abhirpat** [comment]
Thanks for testing this @seano10. Could you please confirm if the error message in sorry page is still "Check IAM roles"? Also to confirm, you have tried to Login again in incognito (or clear browser cache ) to ensure it new session?

**Comment by abhirpat** [comment]
Thanks @seano10 . I also deployed in eu-west-2 (your region) in addition to us-east-1 and us-west-2 but it's working on my end. Could we try updating OpenSearchDashboardsRole > Trust RelationShip > add additional Condition
```
      "ForAnyValue:StringLike": {
        "cognito-identity.amazonaws.com:amr": "authenticated"
      }
```

Also, please verify it  like this where `identity-pool-id` is identity pool in your Cognito > Identity Pools > OpenSearchDashboardsIdPool

```
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {
      "Federated": "cognito-identity.amazonaws.com"
    },
    "Action": "sts:AssumeRoleWithWebIdentity",
    "Condition": {
      "StringEquals": {
        "cognito-identity.amazonaws.com:aud": "identity-pool-id"
      },
      "ForAnyValue:StringLike": {
        "cognito-identity.amazonaws.com:amr": "authenticated"
      }
    }
  }]
}
```

**Comment by seano10** [comment]
Hi @abhirpat sorry to say that even with the additional condition and having confirmed the trust relationship, still the same error :-(

**Comment by abhirpat** [comment]
Thank you for all your effort, Sean. It seems we will need to set up a troubleshooting session to investigate further. Could you please reach out to AWS support and request them to send your ticket to the QnABot team? Once we have your ticket, we can schedule a meeting to investigate further.

**Comment by seano10** [comment]
Hi @abhirpat thanks for  your help with this.  I am due to finish with the client I am working with tomorrow and there is no one to hand this over to so I am going to suggest you close the ticket as resolved rather than me trying to setup a troubleshooting session.

I think it is unlikely they will continue to use the QnA bot for very long after I have gone so it is unlikely anyone will pick up and run with this issue, they have accepted that they cannot see the historic data, but that does negate much of the usefulness of this solution.

**Comment by abhirpat** [comment]
@seano10 Sorry about your experience. Would it help to try a new deployment to demonstrate it to the client? I’m not sure if something went wrong or if any changes were made to the defaults, which would require further troubleshooting. Also, these metrics are permanently stored in the Metrics Bucket. The ones you see in OpenSearch Dashboards are retained based on the OpenSearchDashBoardRetentionMinutes parameter, which is set to 30 days window by default.

**Comment by seano10** [comment]
@abhirpat No worries, I did wonder about uninstalling and starting again, but wasn't sure if the historic data would be retained or not.  I will see how today goes, but I am also nervous of doing that on my last day with no one to pick up the pieces if something should go wrong.  I'll see how the day pans out and update you later.

**Comment by seano10** [comment]
@abhirpat final update from me.  With the other loose ends I have been tidying up this morning I am going to leave this one as is.  As I said, I don't really want to make any changes on my last day and whilst uninstalling and re-deploying should be straight-forward I don't want to risk it.

Sincerely thanks for your help on this and previous issues
Sean

**Comment by abhirpat** [comment]
Thank you for the update @seano10. We will go ahead and archive the case as you mentioned.
